### ISSUE TITLE
Probs About Time for a Slerp

### ISSUE THREAD

**Issue by cwfitzgerald** [kainino0x/gpuinfo-vulkan-query#16]
It's been about a year since the database was updated and there are fun new vulkan things, probably worth a slerp.

**Comment by kainino0x** [comment]
@toji I think you did one recently, could you upload it?

**Comment by toji** [comment]
Hm... I thought I already did? I'll look into that today.

**Comment by kainino0x** [comment]
Oh, you did! I tried to check [here](https://github.com/kainino0x/gpuinfo-vulkan-reports-mirror/commits/main/) but I think I misread the date. It's just this repo needs a submodule update.

**Comment by kainino0x** [comment]
Done, and I'll run another slurp too.
